### ISSUE TITLE
ONNX opset version 12 is not supported

### ISSUE THREAD

**Issue by valenbase** [fabio-sim/LightGlue-ONNX#19]
Deploying the model to another embedded platform, but the embedded platform only supports opset <=12, so setting the opset_version in export.py to 12 gets the error.

**Comment by fabio-sim** [comment]
Hi @valenbase , thank you for your interest in LightGlue-ONNX!

There were several reasons as to why `opset_version=16` is used as the default export:
- SuperPoint uses the `GridSample` operation, for which support was introduced in version 16
- ONNX support for `aten::scaled_dot_product_attention` in LightGlue requires version 14
- LightGlue has now been updated to use `unflatten` operations in the original repo, requiring version 13; this fork still keeps the `einops.rearrange`, but I'm not sure when I'll be syncing this fork with those changes.

However, if you don't mind using DISK instead of SuperPoint, I managed to export the DISK extractor and LightGlue to opset version 12 (with `--dynamic`):
- [disk_opset12.onnx](https://drive.google.com/file/d/1JHkyIkrUY9EfmpJrBepsQof5ZR63o0G9/view?usp=sharing)
- [disk_lightglue_opset12.onnx](https://drive.google.com/file/d/1f74ladpKjWzMq2JOX1rvM3znxPdklhUP/view?usp=sharing)

I hope you find these models helpful!

**Comment by fabio-sim** [comment]
Here you go:

- [disk_lightglue_end2end_opset12.onnx](https://drive.google.com/file/d/1CXM-VtIiFVPXYnvAGCJHaWNytgmkT0YJ/view?usp=sharing)

In case anyone would like to reproduce LightGlue ONNX with opset 12 compatibility, these are the changes required (using [release v0.1.3](https://github.com/fabio-sim/LightGlue-ONNX/tree/v0.1.3) as a reference point):
1. Modify LightGlue's Attention module forward to always use the `einsum` branch instead of the `scaled_dot_product_attention` branch (e.g., by removing the `if` branch):
https://github.com/fabio-sim/LightGlue-ONNX/blob/e82a1a414fe72eb13d5be9c6b026d3e106bb5421/lightglue_onnx/lightglue.py#L66-L76
2. Modify the `opset_version` in [`export.py`](https://github.com/fabio-sim/LightGlue-ONNX/blob/v0.1.3/export.py) from 16 to 12. Note that there are multiple occurrences of `torch.onnx.export()`.
3. Run the export:
```bash
python export.py --extractor_type disk --dynamic --end2end
```
