### ISSUE TITLE
Question of Running Time

### ISSUE THREAD

**Issue by Vincentqyw** [fabio-sim/LightGlue-ONNX#2]
Good job!  Your engineering skills are solid. It's fantastic that you could write the ONNX version for LightGlue just two days after it was open-sourced!
BTW, do you compare the running time between PyTorch and ONNX inference?

**Comment by fabio-sim** [comment]
Thank you for your kind words!

Benchmarking is definitely on my wish list! I'll see if I can get around to it, although a fair comparison may not be possible due to the differences between both versions. Originally the intention of exporting to ONNX was to create a framework-agnostic version of LightGlue (e.g., be able to deploy in C/C++, etc.). I would suspect that with all the available optimisations built into PyTorch already (e.g., mixed-precision, `torch.compile()`, flash attention, etc.), it's most likely faster than the ONNX version.

**Comment by Vincentqyw** [comment]
Looking forward to it.

**Comment by fabio-sim** [comment]
Hi @Vincentqyw , I've provided a preliminary comparison of the inference times. I hope you find it useful in your work!

**Comment by Vincentqyw** [comment]
Great! Very detailed report!
