### ISSUE TITLE
SuperPoint detection threshold and low matching speed

### ISSUE THREAD

**Issue by goktugyildirim4d** [fabio-sim/LightGlue-ONNX#23]
In the case of setting SuperPoint detection_threshold to 0.05, LightGlue matching tooks lots of time sometimes. Why this can be happen? I guess it's due to extracted keypoint count is not equal to 512.

**Comment by fabio-sim** [comment]
Hi @goktugyildirim4d 

From your other issue, I'm assuming this happens when the TensorRT Execution Provider is used. The only explanation I can think of is that TensorRT encounters an unexpected shape and has to rebuild the engine/profile.

Are you using the TRT options like those passed [here](https://github.com/fabio-sim/LightGlue-ONNX/blob/main/evaluation/EVALUATION.md#tensorrt)? If so, you can try to confirm that the number of keypoints returned by SuperPoint does indeed fall in the range between 1 and `max_num_keypoints`.

**Comment by goktugyildirim4d** [comment]
Thanks for your reply. I missed TRT options. I think it's better to use those options in the readme at master branch
